import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.imageio.ImageIO;
//import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.lang.System;
//import javax.swing.JPasswordField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author behnam
 */
public class MainFrame extends javax.swing.JFrame {
    private static Cryptor cr;
    private static final String chosen_dir = null;
    private static final String chosen_file = null;
    private static final String chosen_name = null;
    private static int isEncryptionPasswordHidden = 1;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        DecryptMenu = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        EncryptMenu = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        DecryptDir = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dir_to_decrypt = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        decryptionKey2 = new javax.swing.JPasswordField();
        decryptionMessage2 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        DecryptFile = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        file_to_decrypt = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        decryptionKey = new javax.swing.JPasswordField();
        decryptionMessage = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        EncryptFile = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        file_to_encrypt = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        encryptionKey = new javax.swing.JPasswordField();
        encryptionMessage = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        EncryptDir = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dir_to_encrypt = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        encryptionKey2 = new javax.swing.JPasswordField();
        encryptionMessage2 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kryptonite");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        MainPanel.setPreferredSize(new java.awt.Dimension(300, 400));
        MainPanel.setLayout(new java.awt.CardLayout());

        jButton1.setText("Encrypt");
        jButton1.setAlignmentX(0.7F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Decrypt");
        jButton3.setAlignmentX(0.7F);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.setAlignmentX(0.7F);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setText("About");
        jButton9.setAlignmentX(0.7F);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(30, 30, 30)
                .addComponent(jButton9)
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(MainMenu, "MainMenu");

        DecryptMenu.setPreferredSize(new java.awt.Dimension(400, 300));
        DecryptMenu.setVerifyInputWhenFocusTarget(false);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton12.setText("Decrypt File");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Decrypt Directory");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DecryptMenuLayout = new javax.swing.GroupLayout(DecryptMenu);
        DecryptMenu.setLayout(DecryptMenuLayout);
        DecryptMenuLayout.setHorizontalGroup(
            DecryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptMenuLayout.createSequentialGroup()
                .addGroup(DecryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DecryptMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addGroup(DecryptMenuLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(DecryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DecryptMenuLayout.setVerticalGroup(
            DecryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptMenuLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton12)
                .addGap(69, 69, 69)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        MainPanel.add(DecryptMenu, "DecryptMenu");

        EncryptMenu.setPreferredSize(new java.awt.Dimension(400, 300));
        EncryptMenu.setVerifyInputWhenFocusTarget(false);

        jButton10.setText("Encrypt Directory");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Encrypt File");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EncryptMenuLayout = new javax.swing.GroupLayout(EncryptMenu);
        EncryptMenu.setLayout(EncryptMenuLayout);
        EncryptMenuLayout.setHorizontalGroup(
            EncryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptMenuLayout.createSequentialGroup()
                .addGroup(EncryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncryptMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5))
                    .addGroup(EncryptMenuLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(EncryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EncryptMenuLayout.setVerticalGroup(
            EncryptMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptMenuLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton11)
                .addGap(45, 45, 45)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        MainPanel.add(EncryptMenu, "EncryptMenu");

        DecryptDir.setPreferredSize(new java.awt.Dimension(400, 300));
        DecryptDir.setVerifyInputWhenFocusTarget(false);

        jButton15.setText("Browse ...");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Decrypt Directory");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypt_dir_clicked(evt);
            }
        });

        jLabel5.setText("Enter decryption key:");

        jButton18.setText("Back");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Show Password");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DecryptDirLayout = new javax.swing.GroupLayout(DecryptDir);
        DecryptDir.setLayout(DecryptDirLayout);
        DecryptDirLayout.setHorizontalGroup(
            DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptDirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DecryptDirLayout.createSequentialGroup()
                        .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DecryptDirLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(DecryptDirLayout.createSequentialGroup()
                                .addComponent(dir_to_decrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(decryptionKey2)
                                .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(DecryptDirLayout.createSequentialGroup()
                        .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18)
                            .addComponent(decryptionMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        DecryptDirLayout.setVerticalGroup(
            DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptDirLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(dir_to_decrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(DecryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(decryptionKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3)
                .addGap(29, 29, 29)
                .addComponent(decryptionMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(46, 46, 46)
                .addComponent(jButton18)
                .addContainerGap())
        );

        MainPanel.add(DecryptDir, "DecryptDir");

        DecryptFile.setPreferredSize(new java.awt.Dimension(400, 300));
        DecryptFile.setVerifyInputWhenFocusTarget(false);

        jButton19.setText("Browse ...");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Decrypt File");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter decryption key:");

        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        decryptionKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptionKeyActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Show Password");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DecryptFileLayout = new javax.swing.GroupLayout(DecryptFile);
        DecryptFile.setLayout(DecryptFileLayout);
        DecryptFileLayout.setHorizontalGroup(
            DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DecryptFileLayout.createSequentialGroup()
                        .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DecryptFileLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(93, 93, 93))
                            .addGroup(DecryptFileLayout.createSequentialGroup()
                                .addComponent(file_to_decrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(decryptionKey)
                                .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(139, 139, 139))
                    .addGroup(DecryptFileLayout.createSequentialGroup()
                        .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decryptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17))
                        .addGap(0, 41, Short.MAX_VALUE))))
        );
        DecryptFileLayout.setVerticalGroup(
            DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptFileLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19)
                    .addComponent(file_to_decrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(DecryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(decryptionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4)
                .addGap(40, 40, 40)
                .addComponent(decryptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton20)
                .addGap(46, 46, 46)
                .addComponent(jButton17)
                .addContainerGap())
        );

        MainPanel.add(DecryptFile, "DecryptFile");

        EncryptFile.setPreferredSize(new java.awt.Dimension(400, 300));
        EncryptFile.setVerifyInputWhenFocusTarget(false);

        jButton2.setText("Browse ...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Encrypt File");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_file_clicked(evt);
            }
        });

        jLabel1.setText("Enter encryption key:");

        jButton21.setText("Back");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Show Password");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EncryptFileLayout = new javax.swing.GroupLayout(EncryptFile);
        EncryptFile.setLayout(EncryptFileLayout);
        EncryptFileLayout.setHorizontalGroup(
            EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncryptFileLayout.createSequentialGroup()
                        .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EncryptFileLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(EncryptFileLayout.createSequentialGroup()
                                .addComponent(file_to_encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(encryptionKey)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(EncryptFileLayout.createSequentialGroup()
                        .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton21)
                            .addComponent(encryptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        EncryptFileLayout.setVerticalGroup(
            EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptFileLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(file_to_encrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(EncryptFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(encryptionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jToggleButton1)
                .addGap(40, 40, 40)
                .addComponent(encryptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(41, 41, 41)
                .addComponent(jButton21)
                .addContainerGap())
        );

        MainPanel.add(EncryptFile, "EncryptFile");

        EncryptDir.setPreferredSize(new java.awt.Dimension(400, 300));
        EncryptDir.setVerifyInputWhenFocusTarget(false);

        jButton8.setText("Browse ...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Show Password");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton14.setText("Encrypt Directory");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter encryption key:");

        jButton22.setText("Back");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EncryptDirLayout = new javax.swing.GroupLayout(EncryptDir);
        EncryptDir.setLayout(EncryptDirLayout);
        EncryptDirLayout.setHorizontalGroup(
            EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptDirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncryptDirLayout.createSequentialGroup()
                        .addComponent(dir_to_encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(EncryptDirLayout.createSequentialGroup()
                        .addGroup(EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton22)
                            .addGroup(EncryptDirLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(93, 93, 93)
                                .addGroup(EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(encryptionKey2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(encryptionMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        EncryptDirLayout.setVerticalGroup(
            EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptDirLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(dir_to_encrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(EncryptDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(encryptionKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(encryptionMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton14)
                .addGap(12, 12, 12)
                .addComponent(jButton22)
                .addContainerGap())
        );

        MainPanel.add(EncryptDir, "EncryptDir");
        EncryptDir.getAccessibleContext().setAccessibleParent(EncryptDir);

        About.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jLabel7.setText("Kryptonite");

        jLabel8.setText("Created by Behnam Azizi");

        jLabel11.setText("File Encryption Utility");

        jLabel12.setText("v 1.0.0");

        jButton23.setText("Back");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon.png"))); // NOI18N

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton23))
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AboutLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel12))
                            .addGroup(AboutLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel11))
                            .addComponent(jLabel7)))
                    .addGroup(AboutLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(98, 98, 98)
                .addComponent(jButton23)
                .addContainerGap())
        );

        MainPanel.add(About, "About");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout card =  (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "EncryptMenu");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout card =  (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "DecryptMenu");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout card =  (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "MainMenu");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "About");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "MainMenu");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        String selected_file = "";
        int returnVal = chooser.showOpenDialog(MainMenu);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            selected_file = chooser.getSelectedFile().getAbsolutePath();
        }
        file_to_encrypt.setText(selected_file);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "EncryptFile");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        String selected_file = "";
        int returnVal = chooser.showOpenDialog(MainMenu);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            selected_file = chooser.getSelectedFile().getAbsolutePath();
        }
        dir_to_encrypt.setText(selected_file);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        String selected_file = "";
        int returnVal = chooser.showOpenDialog(MainMenu);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            selected_file = chooser.getSelectedFile().getAbsolutePath();
        }
        dir_to_decrypt.setText(selected_file);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        JFileChooser chooser = new JFileChooser();
        String selected_file = "";
        int returnVal = chooser.showOpenDialog(MainMenu);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            selected_file = chooser.getSelectedFile().getAbsolutePath();
        }
        file_to_decrypt.setText(selected_file);

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "EncryptDir");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "DecryptFile");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "DecryptDir");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "DecryptMenu");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "DecryptMenu");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "EncryptMenu");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "EncryptMenu");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "MainMenu");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void encrypt_file_clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_file_clicked
        String message = "An error occured";
        decryptionKey.setText(new String(encryptionKey.getPassword()));
        decryptionKey2.setText(new String(encryptionKey.getPassword()));
        file_to_decrypt.setText(file_to_encrypt.getText());
        
        try {
            message = Cryptor.encrypt_file(new String(encryptionKey.getPassword()), file_to_encrypt.getText());
        } catch (IOException | NoSuchAlgorithmException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        encryptionMessage.setText(message);
    }//GEN-LAST:event_encrypt_file_clicked

    private void decryptionKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptionKeyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_decryptionKeyActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        String message = "An error occured";
        encryptionKey.setText(new String(decryptionKey.getPassword()));
        encryptionKey2.setText(new String(decryptionKey.getPassword()));
        file_to_encrypt.setText(file_to_decrypt.getText());
        
        try {
            message = Cryptor.decrypt_file(new String(decryptionKey.getPassword()), file_to_decrypt.getText());
        } catch (IOException | NoSuchAlgorithmException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        decryptionMessage.setText(message);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String message = "An error occured";
        decryptionKey.setText(new String(encryptionKey.getPassword()));
        decryptionKey2.setText(new String(encryptionKey.getPassword()));
        dir_to_decrypt.setText(dir_to_encrypt.getText());
        
        try {
            message  = Cryptor.encrypt_dir(new String(encryptionKey2.getPassword()), dir_to_encrypt.getText());
        } catch (IOException | NoSuchAlgorithmException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, message, "Encryption Results", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void decrypt_dir_clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypt_dir_clicked
        String message = "An error occured";
        encryptionKey.setText(new String(decryptionKey2.getPassword()));
        encryptionKey2.setText(new String(decryptionKey2.getPassword()));
        dir_to_encrypt.setText(dir_to_decrypt.getText());

        try {
            message  = Cryptor.decrypt_dir(new String(decryptionKey2.getPassword()), dir_to_decrypt.getText());
        } catch (IOException | NoSuchAlgorithmException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, message, "Decryption Results", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_decrypt_dir_clicked

    private void changePasswordHiddenState(){
        isEncryptionPasswordHidden = 1 - isEncryptionPasswordHidden;
        if (isEncryptionPasswordHidden == 0){
            encryptionKey.setEchoChar((char) 0);
            encryptionKey2.setEchoChar((char) 0);
            decryptionKey.setEchoChar((char) 0);
            decryptionKey2.setEchoChar((char) 0);

            jToggleButton1.setSelected(true);
            jToggleButton2.setSelected(true);
            jToggleButton3.setSelected(true);
            jToggleButton4.setSelected(true);

        }else{
            decryptionKey.setEchoChar('*');            
            decryptionKey2.setEchoChar('*');            
            encryptionKey.setEchoChar('*');            
            encryptionKey2.setEchoChar('*');            

            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);

        }        
    }
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.changePasswordHiddenState();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.changePasswordHiddenState();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        this.changePasswordHiddenState();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        this.changePasswordHiddenState();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, NoSuchAlgorithmException {
        if(args.length == 3){
            if(args[0].equals("-ef")){
                Cryptor.encrypt_file(args[2], args[1]);
                return;
            }else if(args[0].equals("-ed")){
                Cryptor.encrypt_dir(args[2], args[1]);
                return;          
            }else if(args[0].equals("-df")){
                Cryptor.decrypt_file(args[2], args[1]);
                return;
            }else if(args[0].equals("-dd")){
                Cryptor.decrypt_dir(args[2], args[1]);
                return;          
            }
        }
        String help = "Command line usage examples:\n"
                + "Encrypt directory:\n     "
                + "java -jar Kryptonite.jar -ed /PATH/TO/DIR \"PASSWORD\"\n\n"
                + "Encrypt file:\n     "
                + "java -jar Kryptonite.jar -ef /PATH/TO/FILE \"PASSWORD\"\n\n"                
                + "Decrypt directory:\n     "
                + "java -jar Kryptonite.jar -dd /PATH/TO/DIR \"PASSWORD\"\n\n"
                + "Decrypt file:\n     "
                + "java -jar Kryptonite.jar -df /PATH/TO/FILE \"PASSWORD\"\n\n";
;
        System.out.println(help);
        if(args.length == 1 && args[0].equals("-h")) return;

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainFrame main = new MainFrame();
                main.setVisible(true);
                //ImageIcon icon = new ImageIcon(getClass().getResource("/icons/icon.png"));
                main.setIconImage(Toolkit.getDefaultToolkit().getImage("./icon.png"));
            }
        });
 
        
        System.out.println(args[0]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JPanel DecryptDir;
    private javax.swing.JPanel DecryptFile;
    private javax.swing.JPanel DecryptMenu;
    private javax.swing.JPanel EncryptDir;
    private javax.swing.JPanel EncryptFile;
    private javax.swing.JPanel EncryptMenu;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPasswordField decryptionKey;
    private javax.swing.JPasswordField decryptionKey2;
    private javax.swing.JLabel decryptionMessage;
    private javax.swing.JLabel decryptionMessage2;
    private javax.swing.JLabel dir_to_decrypt;
    private javax.swing.JLabel dir_to_encrypt;
    private javax.swing.JPasswordField encryptionKey;
    private javax.swing.JPasswordField encryptionKey2;
    private javax.swing.JLabel encryptionMessage;
    private javax.swing.JLabel encryptionMessage2;
    private javax.swing.JLabel file_to_decrypt;
    private javax.swing.JLabel file_to_encrypt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
